# Generated by Django 4.2.7 on 2026-02-21 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='logomarca',
            field=models.ImageField(blank=True, null=True, upload_to='configuracoes/empresa/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Logomarca'),
        ),
    ]
