# Generated by Django 4.2.7 on 2026-03-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordens_servico', '0017_statusorcamento_movimenta_estoque_saida'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='saldo_estoque',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Saldo em estoque'),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('status_orcamento', 'Status de orçamento')], default='manual', max_length=30, verbose_name='Origem')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('saldo_anterior', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Saldo anterior')),
                ('saldo_posterior', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Saldo posterior')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do registro')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='ordens_servico.orcamento', verbose_name='Orçamento vinculado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='produtos.produto', verbose_name='Produto')),
                ('status_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='ordens_servico.statusorcamento', verbose_name='Status que gerou a movimentação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-data_registro', '-id'],
            },
        ),
    ]
