# Generated by Django 4.2.7 on 2026-03-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_alter_configuracaoempresa_nome_exibicao_menu'),
        ('produtos', '0002_produto_saldo_estoque_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueProdutoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Saldo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da atualização')),
            ],
            options={
                'verbose_name': 'Estoque do produto por empresa',
                'verbose_name_plural': 'Estoques dos produtos por empresa',
            },
        ),
        migrations.RemoveField(
            model_name='produto',
            name='saldo_estoque',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque_produtos', to='configuracoes.configuracaoempresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['empresa', 'produto', 'data_registro'], name='produtos_mo_empresa_068520_idx'),
        ),
        migrations.AddField(
            model_name='estoqueprodutoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_produtos', to='configuracoes.configuracaoempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='estoqueprodutoempresa',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_por_empresa', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AddConstraint(
            model_name='estoqueprodutoempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'produto'), name='produtos_estoque_empresa_produto_uniq'),
        ),
    ]
