# Generated by Django 4.2.7 on 2026-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0003_itemorcamento_orcamento_remove_ordemservico_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor ou percentual conforme acrescimo_tipo', max_digits=10, verbose_name='Acréscimo'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='acrescimo_tipo',
            field=models.CharField(choices=[('valor', 'Valor Fixo'), ('percentual', 'Percentual')], default='valor', max_length=10, verbose_name='Tipo de Acréscimo'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor ou percentual conforme desconto_tipo', max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='desconto_tipo',
            field=models.CharField(choices=[('valor', 'Valor Fixo'), ('percentual', 'Percentual')], default='valor', max_length=10, verbose_name='Tipo de Desconto'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do Orçamento'),
        ),
    ]
