# Generated by Django 4.2.7 on 2026-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0004_add_desconto_acrescimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Opcional - os itens já descrevem o orçamento', null=True, verbose_name='Descrição dos Serviços'),
        ),
    ]
