# Generated by Django 4.2.7 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0005_descricao_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
