# Generated by Django 4.2.7 on 2026-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0016_itempeca_sem_produto_para_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorcamento',
            name='movimenta_estoque_saida',
            field=models.BooleanField(default=False, help_text='Quando marcado, ao selecionar este status o sistema registra saída de estoque dos itens de produto.', verbose_name='Movimenta estoque (saída)'),
        ),
    ]
