# Generated by Django 4.2.7 on 2026-02-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ativo', 'razao_social'], name='clientes_cl_ativo_794ed4_idx'),
        ),
    ]
